### ISSUE TITLE
Sometimes $1 is left in conversion

### ISSUE THREAD

**Issue by bazzadp** [othree/smartypants.js#9]
For example take the following node script:

```javascript
var smartypants = require('smartypants');

var attr = 1; // Number or string
var sourceText = "<i>Custer</i>'s Last Stand!";

var educated = smartypants.smartypants(sourceText, attr);

console.log(educated);
```

This prints out this:
```
<i>Custer</i>$1&#8217;s Last Stand!
```

When it should print out this:

```
<i>Custer</i>&#8217;s Last Stand!
```

Weirdly it looks like this was considered and should be handled:

https://github.com/othree/smartypants.js/blob/3e0ca81cd8dc332435a02679babcb796538f82df/smartypants.js#L474-L485

Is that `$1` in line 485 supposed to be there since it's a lookahead so we don't actually want to inject the match?

**Comment by bazzadp** [comment]
Does this one also need changed?

https://github.com/othree/smartypants.js/blob/8bb3121197bd324b09fcf758e944ef4504931eb3/smartypants.es6.js#L469-L470

And does fixing the es6 file also fix the .js, .mjs and .ts files?

**Comment by othree** [comment]
@bazzadp Thank you. I have fixed this issue and the build issue. Please take a look.

https://github.com/othree/smartypants.js/commit/8bb3121197bd324b09fcf758e944ef4504931eb3

**Comment by bazzadp** [comment]
That doesn't fix is as far as I can tell. It only fixed smartypants.es6.js and not smartypants.js which I am using. Making the same change there does fix it.

Additionally as I pointed out in my comment above, I think the same issue is present in another line.

**Comment by othree** [comment]
Thank you. I checked again and edited the origin file(should be .ts). Now all file formats should have the fix.

**Comment by bazzadp** [comment]
That looks great now! Thanks!

Looking forward to this being released whenever you get a chance.

**Comment by othree** [comment]
@bazzadp 0.1.2 released. Thanks for your report.

**Comment by bazzadp** [comment]
And thank YOU for maintaining this package!

However getting an error with 0.1.2 - raised #11 for that.
